In [ ]:
import numpy as np

In [ ]:
#Task 1
arr_1 = np.arange(1, 11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Task 2
arr_2 = np.zeros((3, 3))
arr_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Task 3
arr_3 = np.random.randint(1, 11, size=(5, 5))
arr_3

array([[2, 6, 9, 9, 7],
       [3, 9, 2, 4, 4],
       [3, 5, 4, 7, 9],
       [8, 8, 3, 5, 8],
       [7, 8, 5, 7, 9]])

In [ ]:
#Task 4
arr_4 = np.random.random((4, 4))
arr_4

array([[0.45957025, 0.47230059, 0.02564832, 0.4569308 ],
       [0.14871495, 0.85664624, 0.96379375, 0.68109855],
       [0.87712801, 0.16328002, 0.2936023 , 0.5422777 ],
       [0.1854032 , 0.43321955, 0.37462211, 0.99521369]])

In [ ]:
#Task 5
arr_51 = np.random.randint(1, 11, size=(5))
arr_52 = np.random.randint(1, 11, size=(5))

In [ ]:
arr_51

array([3, 2, 2, 8, 7])

In [ ]:
arr_52

array([8, 5, 1, 5, 8])

In [ ]:
result_1 = arr_51 + arr_52
result_2 = arr_51 - arr_52
result_3 = arr_51 * arr_52
print(result_1, result_2, result_3)

[11  7  3 13 15] [-5 -3  1  3 -1] [24 10  2 40 56]


In [ ]:
#Task 6
arr_61 = np.random.randint(1, 11, size=(7))
arr_62 = np.random.randint(1, 11, size=(7))
print(arr_61, arr_62)

[ 5  2  3  3  4 10  5] [10  5  7  9  4  2  7]


In [ ]:
result = np.dot(arr_61, arr_62)
print(result)

179


In [ ]:
#Task 7
arr_71 = np.random.randint(1, 11, size=(2, 2))
arr_72 = np.random.randint(1, 11, size=(2, 3))
res = np.dot(arr_71, arr_72)
print(res)

[[ 66  57  31]
 [120 110  60]]


In [ ]:
#Task 8
arr_8 = np.random.randint(1, 11, size=(3, 3))
res_8 = np.linalg.inv(arr_8)
print(res_8)

[[-2.8  0.5  0.8]
 [ 2.6 -0.5 -0.6]
 [-1.9  0.5  0.4]]


In [ ]:
#Task 9
arr_9 = np.random.random(size=(4, 4))
res_9 = np.transpose(arr_9)
print(res_9)

[[0.99982326 0.01951015 0.63542452 0.1714515 ]
 [0.29043777 0.725313   0.01131315 0.5305239 ]
 [0.74089147 0.60929001 0.51141043 0.05467209]
 [0.1808149  0.34370567 0.29616204 0.04243566]]


In [ ]:
#Task 10
arr_101 = np.random.randint(1, 11, size=(3, 4))
arr_102 = np.random.randint(1, 11, size=(4))
res_10 = np.dot(arr_101, arr_102)
print(res_10)

[ 96 103 100]


In [ ]:
#Task 11
arr_111 = np.random.random(size=(2, 3))
arr_112 = np.random.random(size=(3))
res_11 = np.dot(arr_111, arr_112)
print(res_11)

[0.47969062 0.74341276]


In [ ]:
#Task 12
arr_121 = np.random.randint(1, 11, size=(2, 2))
arr_122 = np.random.randint(1, 11, size=(2, 2))
res_12 = np.multiply(arr_121, arr_122)
print(res_12)

[[36 32]
 [30 40]]


In [ ]:
#Task 13
arr_131 = np.random.randint(1, 11, size=(2, 2))
arr_132 = np.random.randint(1, 11, size=(2, 2))
res_13 = np.dot(arr_131, arr_132)
print(res_13)

[[121  54]
 [ 90  44]]


In [ ]:
#Task 14
arr_14 = np.random.randint(1, 101, size=(5, 5))
res_14 = np.sum(arr_14)
print(res_14)

1308


In [ ]:
#Task 15
arr_151 = np.random.randint(1, 11, size=(4, 4))
arr_152 = np.random.randint(1, 11, size=(4, 4))
res_15 = arr_151 - arr_152
print(res_15)

[[ 7  5  9 -4]
 [-2  6  2 -1]
 [ 6 -5 -4 -3]
 [ 6 -7  7 -1]]


In [40]:
#Task 16
arr_16 = np.random.random(size=(3, 3))
sum_vector = np.sum(arr_16, axis=1)
res_16 = sum_vector.reshape(-1, 1)
print(res_16)

[[1.99891723]
 [1.94665974]
 [1.47531965]]


In [ ]:
#Task 17
arr_17 = np.random.randint(1, 11, size=(3, 4))
res_17 = np.square(arr_17)
print(res_17)

[[ 64  81   1  49]
 [  1 100 100  81]
 [ 16  64   4   9]]


In [ ]:
#Task 18
arr_18 = np.random.randint(1, 51, size=(4))
res_18 = np.sqrt(arr_18)
print(res_18)

[4.79583152 6.08276253 1.73205081 2.        ]
